# Generated by Django 5.0.6 on 2024-05-15 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('authors', models.ManyToManyField(related_name='autorzy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=100)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squares', to='images.picture')),
            ],
        ),
    ]
