# Generated by Django 5.0.6 on 2024-05-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_name_rectangle_delete_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.CharField(default='', max_length=500),
        ),
    ]
